services:
  user-service-1:
    build: ./services/user-service
    depends_on:
      - rabbitmq
    environment:
      - CONTAINER_ID=container1
    ports:
      - "3001:3000"
    networks:
      - app-network

  user-service-2:
    build: ./services/user-service
    depends_on:
      - rabbitmq
    environment:
      - CONTAINER_ID=container2
    ports:
      - "3002:3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/static:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - user-service-1
      - user-service-2
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
