services:
  user-service:
    build: ./services/user-service
    ports:
      - "3001:3001"
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - user-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
